import Head from "next/head";
import Calendar from "../components/Calendar";
import { formatISO } from "date-fns";
import { db } from "~/server/db";
import { Day } from "@prisma/client";
import { GetServerSideProps, NextPage } from "next";

interface HomeProps {
  days: Day[];
  closedDays: string[]; // as ISO strings
}

const Home: NextPage<HomeProps> = ({ days, closedDays }) => {
  return (
    <>
      <Head>
        <title>Restaurant Booking Software</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Calendar days={days} closedDays={closedDays} />
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const days = await db.day.findMany();
  const closedDays = (await db.closedDay.findMany()).map((d) =>
    formatISO(d.date)
  );

  return { props: { days, closedDays } };
};

export default Home;
